version: '3.9'

volumes:
  db-store:

services:

  db:
    container_name: 'react-learning-db'
    build:
      context: .
      dockerfile: ./containers/mariadb/Dockerfile    
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    ports:
      - target: 3306
        published: ${DB_PORT:-3307}
        protocol: tcp
        mode: host

    environment:
      - MYSQL_DATABASE=${DB_NAME:-alphacamp}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
      - MYSQL_ROOT_HOST=%

    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - react-learning-network

  app:
    container_name: 'react-learning-app'
    build:
      context: .
      dockerfile: ./containers/js/Dockerfile    
    ports:
      - target: 3000
        published: ${FRONT_PORT:-3000}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
        consistency: delegated
    depends_on:
      db:
        condition: service_healthy

    tty: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-alphacamp}
      - DB_USERNAME=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    
    networks:
      - react-learning-network

networks:
  react-learning-network:
    driver: bridge
