version: '3.9'

volumes:
  db-store:

services:

  front:
    container_name: 'articlecamp-front'
    build:
      context: .
      dockerfile: ./containers/js-front/Dockerfile    
    ports:
      - target: 3000
        published: ${FRONT_PORT:-3000}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./articlecamp-front
        target: /usr/src/app
        consistency: delegated

    tty: true
    # environment:
    #   - DB_CONNECTION=mysql
    #   - DB_HOST=db
    #   - DB_PORT=3306
    #   - DB_DATABASE=${DB_NAME:-articlecamp}
    #   - DB_USERNAME=${DB_USER:-root}
    #   - DB_PASSWORD=${DB_PASSWORD:-password}
    
    networks:
      - articlecamp-network

  back:
    container_name: 'articlecamp-back'
    build:
      context: .
      dockerfile: ./containers/js-back/Dockerfile    
    ports:
      - target: 5000
        published: ${BACK_PORT:-5000}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./articlecamp-back
        target: /usr/src/app
        consistency: delegated
    depends_on:
      db:
        condition: service_healthy

    tty: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-articlecamp}
      - DB_USERNAME=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    
    networks:
      - articlecamp-network

  db:
    container_name: 'articlecamp-db'
    build:
      context: .
      dockerfile: ./containers/mariadb/Dockerfile    
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    ports:
      - target: 3306
        published: ${DB_PORT:-3307}
        protocol: tcp
        mode: host

    environment:
      - MYSQL_DATABASE=${DB_NAME:-articlecamp}
      - MYSQL_USER=${DB_USER:-admin}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-password}
      - MYSQL_ROOT_HOST=%

    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - articlecamp-network

networks:
  articlecamp-network:
    driver: bridge
